name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract version
      id: version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV"
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build (Release)
      run: dotnet build -c Release --no-restore -p:Version=${{ env.VERSION }}

    # - name: Test
    #   run: dotnet test -c Release --no-build

    - name: Pack (NuGet + Symbols)
      run: |
        dotnet pack \
          -c Release \
          --no-build \
          -p:Version=${{ env.VERSION }} \
          -p:IncludeSymbols=true \
          -p:SymbolPackageFormat=snupkg \
          --output ./artifacts

    # Sign once a certificate is available
    # - name: Code signing
    #   run: dotnet build -c Release -p:SignAssembly=true -p:AssemblyOriginatorKey=key.snk

    - name: Push NuGet package
      run: |
        dotnet nuget push "artifacts/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
    - name: Push Symbols
      run: |
        dotnet nuget push "artifacts/*.snupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
