using System.Collections;
using System.Text;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Contracts;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Extensions;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Wrapper;

namespace DocuWare.Platform.ServerClient.Abstracts.Generation.Services.Generation
{
    internal class EnumGenerationService : IGenerationService
    {
        internal string Template { get; } = @"// <auto-generated>

namespace DocuWare.Platform.ServerClient.Abstracts{namespaceExtension}
{
{documentationComment}    public enum {name}
    {{values}
    }
}";

        public void Generate(Type type)
        {
            string enumName = type.Name;
            Console.WriteLine($"Generating {enumName}.g.cs");

            bool hasBaseType = type.BaseType is not null && type.BaseType.GetTypeDefinition().Category is TypeCategory.Enum;
            string namespaceName = type.Namespace ?? string.Empty;
            string? namespaceExtension = null;

            if (!namespaceName.StartsWith("DocuWare.Platform.ServerClient"))
            {
                string[] namespaceValues = namespaceName.Split('.');
                int indexServerClient = Array.FindIndex(namespaceValues, x => x.Equals("DocuWare", StringComparison.OrdinalIgnoreCase));

                namespaceExtension = string.Join('.', namespaceValues[(indexServerClient + 1)..]);
            }
            else if (!namespaceName.EndsWith("ServerClient"))
            {
                string[] namespaceValues = namespaceName.Split('.');
                int indexServerClient = Array.FindIndex(namespaceValues, x => x.Equals("ServerClient", StringComparison.OrdinalIgnoreCase));

                namespaceExtension = string.Join('.', namespaceValues[(indexServerClient + 1)..]);
            }

            string content = GenerateContent(type, enumName, namespaceExtension);
            WriteFile(content, enumName);
        }

        private string GenerateContent(Type type, string enumName, string? nameSpaceExtension)
        {
            string enumValues = GenerateEnumValues(type);
            string documentationComment = DocumentationCommentsService.GetDocumentationCommentOfType(type);
            return Template.Replace("{documentationComment}", documentationComment)
                           .Replace("{namespaceExtension}", string.IsNullOrEmpty(nameSpaceExtension) ? string.Empty : $".{nameSpaceExtension}")
                           .Replace("{name}", enumName)
                           .Replace("{values}", enumValues);
        }

        private static string GenerateEnumValues(Type type)
        {
            string result = string.Empty;

            Array enumValues = type.GetEnumValues();
            IEnumerator enumerator = enumValues.GetEnumerator();
            bool hasNext = enumerator.MoveNext();

            while (hasNext)
            {
                if (type.Name.Equals("LineStyle"))
                {
                    // TODO Check for cleaner way, temp fix to avoid keyword issues
                    string capitalizedFirstLetter = enumerator.Current.ToString()![0].ToString().ToUpper();
                    ReadOnlySpan<char> lowerCaseRemainingLetters = enumerator.Current.ToString()!.AsSpan(1);

                    string value = string.Concat(capitalizedFirstLetter, lowerCaseRemainingLetters);
                    result += $"{StringConstants.LineEndingWithTwoTabs}{value} = {(int)enumerator.Current}";
                }
                else
                {
                    result += $"{StringConstants.LineEndingWithTwoTabs}{enumerator.Current} = {(int)enumerator.Current}";
                }

                hasNext = enumerator.MoveNext();

                if (hasNext)
                    result += ',';
            }

            return result;
        }

        private static void WriteFile(string content, string enumName)
        {
            using FileStream fStream = File.Create(Path.Combine(Paths.GenerationFolder, $"{enumName}.g.cs"));
            fStream.Write(Encoding.UTF8.GetBytes(content ?? string.Empty));
        }
    }
}
