using System.Reflection;
using System.Text;
using System.Xml.Serialization;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Contracts;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Extensions;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Services.PropertyStrategies;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Templates;
using DocuWare.Platform.ServerClient.Abstracts.Generation.Wrapper;

namespace DocuWare.Platform.ServerClient.Abstracts.Generation.Services.Generation
{
    internal class ImplementationGenerationService(string? namespaceExtension = null) : IGenerationService
    {
        private readonly string? _namespace = namespaceExtension;

        internal string Template { get; } = @"// <auto-generated>

using SDK = DocuWare.Platform.ServerClient;
using DocuWare.Platform.ServerClient.Abstracts.Content;
using DocuWare.Platform.ServerClient.Abstracts.Policy.CircuitBreaker;
using DocuWare.Platform.ServerClient.Abstracts.Policy.Resilience;
using DocuWare.Platform.ServerClient.Abstracts.Policy.Retry;

namespace DocuWare.Platform.ServerClient.Abstracts{namespace}
{
{documentationComment}    public class {classname}({wrappedtype} obj) : {basetype}
    {
        /// <summary>
        /// Gets the wrapped object of the SDK.
        /// </summary>
        internal {wrappedtype} Obj { get; } = obj;{members}
    }
}";

        /// <param name="type"></param>
        public void Generate(Type type)
        {
            Console.WriteLine($"Generating {type.Name}.cs");
            string content = GenerateContent(type);

            WriteFile(content, type.Name);
        }

        private string GenerateContent(Type type)
        {
            TypeDef typeDefinition = type.GetTypeDefinition();

            string fullNSName = typeDefinition.FullName.StartsWith("DocuWare.Platform.ServerClient")
                ? typeDefinition.FullName.Replace("DocuWare.Platform.ServerClient", "SDK")
                : typeDefinition.FullName;

            string documentationComment = DocumentationCommentsService.GetDocumentationCommentOfType(type);
            string propertyList = GenerateProperties(type);
            string methodList = GenerateMethods(type);

            return Template.Replace("{documentationComment}", documentationComment)
                           .Replace("{classname}", typeDefinition.GetTypeName())
                           .Replace("{basetype}", typeDefinition.GetReturnTypeName())
                           .Replace("{wrappedtype}", fullNSName)
                           .Replace("{namespace}", _namespace is not null ? $".{_namespace}" : string.Empty)
                           .Replace("{members}", propertyList + methodList);
        }

        private void WriteFile(string template, string typeName)
        {
            string path = Paths.GenerationFolder;

            if (_namespace is not null)
            {
                string[] nameSpaceBlocks = _namespace.Split('.');

                for (int i = 0; i < nameSpaceBlocks.Length; i++)
                    path = Path.Combine(path, nameSpaceBlocks[i]);

                Directory.CreateDirectory(path);
            }

            using FileStream fStream = File.Create(Path.Combine(path, $"{typeName}.g.cs"));
            fStream.Write(Encoding.UTF8.GetBytes(template ?? string.Empty));
        }

        private static string GenerateProperties(Type type)
        {
            PropertyInfo[] properties = [.. type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
                                                .Where(p => !p.CustomAttributes.Any(a => a.AttributeType == typeof(XmlIgnoreAttribute)))];

            string propertyList = string.Empty;

            for (int i = 0; i < properties.Length; i++)
                GenerateProperty(properties[i], ref propertyList);

            return propertyList;
        }

        // TODO Handle in seperate class for cleaner code - This is quite messy atm
        private static void GenerateProperty(PropertyInfo property, ref string propertyList)
        {
            TypeDef typeDefinition = property.PropertyType.GetTypeDefinition();
            string returnTypeName = typeDefinition.GetReturnTypeName();

            // TODO improve to a more general approach
            if (returnTypeName.Equals("IDictionary"))
                returnTypeName = "System.Collections.IDictionary";

            propertyList += $"{StringConstants.LineEnding}{StringConstants.LineEnding}";

            PropertyGenerationStrategy propertyGenerationStrategy = PropertyGenerationStrategy.FindStrategy(property, typeDefinition);
            DocumentationCommentsService.GetDocumentationCommentOfProperty(property);
            propertyList += propertyGenerationStrategy.Generate(property, returnTypeName, property.Name);
        }

        private static string GenerateMethods(Type type)
        {
            string methodList = string.Empty;
            MethodInfo[] methods = [.. type.GetMethods(BindingFlags.Instance | BindingFlags.Public).Where(m => !m.IsSpecialName || (m.IsVirtual && m.Name.Contains("SetProxy")))];

            for (int i = 0; i < methods.Length; i++)
            {
                MethodInfo method = methods[i];

                if (method.DeclaringType != type && (method.DeclaringType != type.BaseType || (method.DeclaringType == typeof(object) || method.DeclaringType == typeof(Exception))))
                    continue;

                string returnTypeName = method.ReturnType.GetParsedName();

                // Filters generic methods, might need implementation in the future
                if (method.IsGenericMethodDefinition)
                    continue;

                methodList += $"{StringConstants.LineEnding}{StringConstants.LineEnding}";

                if (returnTypeName.StartsWith("Task"))
                    methodList += $"{GenerateAsynchronous(method)}";
                else
                    methodList += $"{GenerateSynchronous(method)}";
            }

            // TODO improve in the future to search for method in nested types. Workaround for now.
            if (type.Name.Equals("DialogPropertiesTaskList"))
                methodList += $"{StringConstants.LineEnding}{StringConstants.LineEnding}\t\tpublic void SetProxy(HttpClientProxy proxy) => Obj.SetProxy(proxy);";

            return methodList;
        }

        private static string GenerateSynchronous(MethodInfo method)
        {
            if (method.Name.Equals("ToString"))
                return "\t\tpublic override string ToString() => Obj.ToString();";

            if (method.Name.Equals("SetProxy"))
                return "\t\tpublic void SetProxy(HttpClientProxy proxy) => Obj.SetProxy(proxy);";

            TypeDef typeDef = method.ReturnType.GetTypeDefinition();
            string returnTypeName = typeDef.GetReturnTypeName();
            string typeName = typeDef.GetTypeName();
            string parameters = method.GetParsedParameterDefinitions();
            string paramsToSent = method.GetParsedParameters();

            bool isDocuWareType = typeDef.Category is TypeCategory.DocuWare;
            if (isDocuWareType)
                return TemplateService.GetSyncDocuWareMethodImplementation(returnTypeName, typeName, method.Name, parameters, paramsToSent);

            bool isDocuWareEnumType = typeDef.Category is TypeCategory.Enum && typeDef.FullName.StartsWith("DocuWare.Platform.ServerClient");
            if (isDocuWareEnumType)
                return TemplateService.GetSyncDocuWareEnumMethodImplementation(returnTypeName, method.Name, parameters, paramsToSent);

            return $"\t\tpublic {returnTypeName} {method.Name}({parameters}) => Obj.{method.Name}({paramsToSent});";
        }

        private static string GenerateAsynchronous(MethodInfo method)
        {
            string parameters = method.GetParsedParameterDefinitions();
            string paramsToSent = method.GetParsedParameters();

            TypeDef returnType = method.ReturnType.GetTypeDefinition();
            string typeName = returnType.GetTypeName();
            string returnTypeName = returnType.GetReturnTypeName();

            TypeDef? innerMostChild = returnType.NestedType;
            while (innerMostChild is not null && innerMostChild.NestedType is not null)
                innerMostChild = innerMostChild.NestedType;

            bool isDwType = innerMostChild is not null && innerMostChild.Category is TypeCategory.DocuWare;

            if (returnTypeName.Equals("Task<IOrganization[]>"))
                return $"\t\tpublic async {returnTypeName} {method.Name}({parameters}) => (await Obj.GetOrganizationsAsync()).ToList().ConvertAll(o => new Organization(o)).ToArray();";

            return isDwType && returnTypeName.Contains("DeserializedHttpResponse<")
                ? GenerateAsyncDeserializedHttpResponseMethod(returnType, typeName, returnTypeName, method, parameters, paramsToSent)
                : $"\t\tpublic async {returnTypeName} {method.Name}({parameters}) => await Obj.{method.Name}({paramsToSent});";
        }

        private static string GenerateAsyncDeserializedHttpResponseMethod(TypeDef returnType, string typeName, string returnTypeName, MethodInfo method, string parameters, string paramsToSent)
        {
            string result = TemplateService.AsyncDocuWareMethod.Replace("{0}", returnTypeName).Replace("{1}", method.Name).Replace("{2}", parameters).Replace("{4}", paramsToSent);

            TypeDef? innerMostChild = returnType.NestedType;
            while (innerMostChild is not null && innerMostChild.NestedType is not null)
                innerMostChild = innerMostChild.NestedType;

            if (innerMostChild is not null)
            {
                result = result.Replace("{3}", innerMostChild.GetTypeName());

                if (innerMostChild.Category is TypeCategory.DocuWare)
                {
                    result = result.Replace("{5}", $"DeserializedHttpResponse<{innerMostChild.FullName}>");
                    result = result.Replace("{6}", $"I{innerMostChild.GetTypeName()}");
                }
                else
                {
                    result = result.Replace("{5}", $"DeserializedHttpResponse<{innerMostChild.GetTypeName()}>");
                    result = result.Replace("{6}", innerMostChild.GetTypeName());
                }
            }
            else
            {
                result = result.Replace("{3}", typeName);
                result = result.Replace("{5}", $"DeserializedHttpResponse<{returnType.GetTypeName()}>");
                result = result.Replace("{6}", returnType.GetTypeName());
            }

            return result;
        }
    }
}
